export const initialData = [
    {
      name: 'Aakash',
      rollno: '1',
      checkin: '1600',
      checkout: '',
    },
    {name:'isha',
      rollno: ' 2',
      checkin: '1700',
      checkout: '1800',
    },
    {name:'lovish',
      rollno: '3',
      checkin: '1800',
      checkout: '',
    },
    {name:'nishtha',
      rollno: '4',
      checkin: '1900',
      checkout: '1930',
    },
    {name:'shivam',
      rollno: '5',
      checkin: '2000',
      checkout: '',
    },
  ];
  